---
language: java
sudo: false
install: true
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk-ea
script:
  - "./bin/cibuild"
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
matrix:
  allow_failures:
    - jdk: openjdk-ea
env:
  global:
    -  # OSSRH_USERNAME
    - secure: "DCOpugGVWyhC1oLYAcAQdJJ9f/lgLACJYYvdWxx6y/26igFAqnOpUUfTZY8K1y5Dvn9s6tCUCIacR8WmBsUWGYeIp7LRY7kNB9w+wfaDMgx53QiYXDQXxG8a7eWCPdLOpS5vfjPnebrEa38V/3nQIVC/ikUF5GB3LHu2tO1kbO0oW4aZrrNrtlgrUTxRhuvDOywKC3YEi13MJFYYwmcPmQzdOl6zJrtlsQWshaXPVthTqQwxdDx6CBFDOXFAATS1AL0QevAraKD6whLFc+zSjBzPCKy7dqinQN0h2qakNo0DJR1CdP4VJF0gCbgl8VMvLkXvD36RmQkmTavEXp8HlR/PO/HF3B3i9o/E5IzhjxurSKsvnVbSXyLUKmCG1EjVg0Mli+GzV6zMUW2VxDRG1+236RbCUd0VumzuvgwB6ClHxZ0G/tx5p3CrxSgG4W4dc2zXvT7M8uLeX4g+YZZmlHwcRB7iSAQfOsvQ5amaMhv3ArcxZe8gPjPie2nMfsWcQyMroiHWrcbA0klbUwQkDP/lcy9Xynl7AgGVk6MU+rehlRCTnzG7jecnRKzGrhs3+/tVOvrmTIJI7iNUFeV8f2++BtvoNEPAdg4mGthXxaJuIJo48VRjZxds7sifGH29N5OYxyShqp4Z0c7qVk2GLNftvbDeMMf9azm6gPzc3hE="
    -  # OSSRH_PASSWORD
    - secure: "J3SI/5fTHVq1Rpishdswt5oqrs8XN9nim92exyncljx72eM5rYBJQU1+spVWpGf7EvKJ4afa8GPzGrsJBo4HdyOJzFc2EKj+vCe+fyiFzyOUr+6k+3NR+3+QhyRdMb9P2K+GC54MhxbvSeN6kIYfhltcNzDnT9YTVeaX3aDLmpLTkNvc603pgFLWFT1ynrJJ0Hb6Ej4KtR89kzCo9VKOZjDkkGyqwzwFZ7AEI798tc29K6KR63LboJZdYzGWvr28sr+8GbNIM/qXyhSt/ZUNeRKD9NTcOHCic1zV1XLFeo9TyHzxRFTMx1F+utsYmsyR94Rp62q63qoyU45pb6vRnOO6TQhflHmUB855hvIj1IFhF756tV4zmzKLFyr+eM5TX5bKClEdi+ZujhWYoMN0lsW6doxQF4zH8yNqmtTwHWoQQfLIOmYJmNIiE/OGf6TEnch3uyE4VlvQAW94+NfKrdrnhLPgvNFaXQ1UlRaz3E9DibrB4EOVUZXEOtmkJAcmDeX4y6P6JhxvBflXV2A5r95xVTUhKDOU7LNpzG64DkvMfl6Jcp1ln7Dbek8148xeQCQSKx+ZpcgIDZNt5NMY9atw2g9n9XromQnx+8IKMY/mJs6R9vCV1unqZljEsL++QQH+NmqbzXwyifjYcjmze+2dfha6eA5InSScwMPciHo="
addons:
  sonarcloud:
    organization: "complate"
    token:
      secure: "oA2jzShS32wFK/8n2YN98B+XAa5+Y7t8dXrleEIxyFRaP4muNWuqrgLAMEOpmkOKFskXrelBGBvEi2vD91LPLpZAhXTDz1b9LI9OAiCo7lPAAQ5UP1CBn3N7VR0fRxtNyjYLvOepwhh9VbFuh5fDmOmxFQptT98oDns/TFrqTUPV6kuyACvjn4aG/0fpxtFNW1RwFGh7ChtXuX70dAz7DqvdFgX0iAt6lcUlh278LM0vDfa997P/rSQ+lee7Z3B6PQ1lUH3a5J3HldTaGTl8pYaSX9JeOsw30bq0JPs/z8VmHh0aL92l/1D0l1xfrVNDL1RzzTv+7pvu7mX+V8L121na39YTdGz3SRmOSgZgMAQgaNOFF4kNjn1bRtyYjPZo5D20LQc8XI77Z0n8FUK0x+ioktCHd5ZC8hA6kJhcoV3y/9g/8+/Ll+CJhLibtH9iTkx301GiWiujZnrb12O5BQj6eWl8tUykXqi7Ywm+zsJG/EC80I2rQ7x6mUZxmvPHpFWqeWwoGQW3kFUzpwE2C3gWxqGm8S+4eylV8zSlqm9Qn0g4d727xBEp5VTikSCDPdWLDESoPoxDQKq/9eXO402aS9u1mL/9fU3FN8vV08DoFtKV9b/jLM8zHa4d3SGe92KZiFhA2rY/NRrdFTtM6iL3+opAHQWFRcDtC32ygbo="
