---
language: java
sudo: false
install: true
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk-ea
script:
  - ./mvnw --batch-mode --errors clean package
cache:
  directories:
    - "$HOME/.m2"
matrix:
  allow_failures:
    - jdk: openjdk-ea
